# Generated by Django 5.1.6 on 2025-03-03 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre y Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de creación')),
                ('contactado', models.BooleanField(default=False, verbose_name='¿Se ha contactado con él?')),
            ],
        ),
    ]
